repos:
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.5.1  # or the latest version of mypy
    hooks:
      - id: mypy
        additional_dependencies:
          [
            "redis==5.0.1",
            "types-requests==2.28.1"
          ]
