version: '2.3'
services:
  local_redis:
    build: redis_data/
    container_name: local_redis
    ports:
      - 6379:6379
    volumes:
      - ./redis_data/:/data
    networks:
      - deploy_network
  local_fastapi:
    build: directai_fastapi/
    ports: 
      - 8000:8000
    networks:
      - deploy_network
    container_name: local_fastapi
    environment:
      - PYTHONUNBUFFERED=1
      - NVIDIA_VISIBLE_DEVICES=all
      - HF_HOME=/.cache/huggingface
    runtime: nvidia
    volumes:
      - ./directai_fastapi/logs:/directai_fastapi/logs
    depends_on:
      - local_redis
    extra_hosts:
      - "host.docker.internal:host-gateway"

networks:
  deploy_network:
    driver: bridge