version: '2.3'
services:
  local_fastapi:
    build: directai_fastapi/
    ports: 
      - 8000:8000
    networks:
      - deploy_network
    container_name: local_fastapi
    environment:
      - PYTHONUNBUFFERED=1
      - NVIDIA_VISIBLE_DEVICES=1
      - HF_HOME=/directai_fastapi/.cache/huggingface
      - CACHE_REDIS_PORT=6379
    env_file:
      - directai_fastapi/.env
    runtime: nvidia
    volumes:
      - ./logs:/directai_fastapi/logs
      - ./.cache:/directai_fastapi/.cache
    shm_size: 10.24g  # because Ray complains if it's less
    extra_hosts:
      - "host.docker.internal:host-gateway"

networks:
  deploy_network:
    driver: bridge
