version: '2.3'
services:
  local_redis_ben:
    build: redis_data/
    container_name: local_redis_ben
    ports:
      - 6371:6379
    volumes:
      - ./redis_data/:/data
    networks:
      - deploy_network
  local_fastapi_ben:
    build: directai_fastapi/
    ports: 
      - 8001:8000
    networks:
      - deploy_network
    container_name: local_fastapi_ben
    environment:
      - PYTHONUNBUFFERED=1
      - NVIDIA_VISIBLE_DEVICES=0
      - HF_HOME=/.cache/huggingface
    env_file:
      - directai_fastapi/.env
    runtime: nvidia
    volumes:
      - ./logs:/directai_fastapi/logs
    shm_size: 10.24g  # because Ray complains if it's less
    depends_on:
      - local_redis_ben
    extra_hosts:
      - "host.docker.internal:host-gateway"
  local_gradio:
    build: gradio/
    networks:
      - deploy_network
    ports: 
      - 7860:7860
    depends_on:
      - local_fastapi_ben
    container_name: local_gradio
    environment:
      - PYTHONUNBUFFERED=1
    extra_hosts:
      - "host.docker.internal:host-gateway"

networks:
  deploy_network:
    driver: bridge
