version: '2.3'
services:
  local_redis_isaac_2:
    build: redis_data/
    container_name: local_redis_isaac_2
    ports:
      - 63790:63790
    volumes:
      - ./redis_data/:/data
    networks:
      - deploy_network
  local_fastapi_isaac_2:
    build: directai_fastapi/
    ports: 
      - 10000:10000
    networks:
      - deploy_network
    container_name: local_fastapi_isaac_2
    environment:
      - PYTHONUNBUFFERED=1
      - NVIDIA_VISIBLE_DEVICES=1
      - HF_HOME=/directai_fastapi/.cache/huggingface
      - CACHE_REDIS_PORT=63790
    env_file:
      - directai_fastapi/.env
    runtime: nvidia
    volumes:
      - ./logs:/directai_fastapi/logs
      - ./.cache:/directai_fastapi/.cache
    shm_size: 10.24g  # because Ray complains if it's less
    depends_on:
      - local_redis_isaac_2
    extra_hosts:
      - "host.docker.internal:host-gateway"

networks:
  deploy_network:
    driver: bridge
