version: '2.3'

services:
  local_tests_ben:
    build: integration_tests/
    container_name: local_tests_ben
    networks:
      - deploy_network
    volumes:
      - ./logs:/logs
    extra_hosts:
    - "host.docker.internal:host-gateway"

networks:
  deploy_network:
    driver: bridge